/**
 * Agency EFT Service API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface TblPriceBookMain { 
    partId?: number;
    sectionId?: number;
    orderId?: number;
    partNumber?: string;
    altPartNumber?: string;
    description?: string;
    longDescription?: string;
    costRule?: string;
    priceRule?: string;
    itemDiscountRule?: string;
    cost?: number;
    price?: number;
    itemDiscount?: number;
    lbcode?: string;
    lbquantity?: number;
    lbcost?: number;
    lbprice?: number;
    lbdiscount?: number;
    units?: string;
    groupName?: string;
    supplierName?: string;
    docName?: string;
    image?: string;
    createdOn?: Date;
    createdBy?: string;
    updatedOn?: Date;
    updatedBy?: string;
    isKit?: boolean;
    viewInWeb?: boolean;
    isAssociated?: boolean;
    showInQuote?: boolean;
    ts?: string;
    isBaseModel?: boolean;
    features?: string;
    materialCost?: number;
    startingMargin?: number;
    supplierCurrency?: string;
    landedCost?: string;
    sellPrice?: string;
    manufacturer?: string;
    category?: string;
    expense?: boolean;
    warehouse?: number;
    showInBom?: boolean;
    xlabourHrs?: string;
}